app/components/edit-absence-modal/template.hbs
app/components/edit-activity-modal/component.js
app/components/edit-activity-modal/template.hbs
app/components/edit-report-modal/component.js
app/components/edit-report-modal/template.hbs
app/components/record-button/component.js
app/components/record-button/styles.scss
app/components/record-button/template.hbs
app/components/task-selection/component.js
app/components/task-selection/template.hbs
app/components/tracking-bar/component.js
app/components/tracking-bar/styles.scss
app/components/tracking-bar/template.hbs
app/index/activities/controller.js
app/index/activities/route.js
app/index/activities/template.hbs
app/index/reports/template.hbs
app/validations/activity.js
tests/acceptance/index-activities-test.js
tests/acceptance/index-test.js
tests/integration/components/edit-absence-modal/component-test.js
tests/integration/components/edit-activity-modal/component-test.js
tests/integration/components/edit-report-modal/component-test.js

Therefore an activity needs to be editable which is now possible too.

Added possibility to start an activity without a task.

---

app/index/route.js

Filter reports by user

---

app/index/activities/route.js
app/index/activities/template.hbs
mirage/factories/activity.js
tests/acceptance/index-activities-test.js

Show warning when reports are generated from unknown tasks

---

app/analysis/controller.js
app/analysis/template.hbs
app/components/form-booking-filter/component.js
app/components/form-booking-filter/template.hbs
app/me/template.hbs
app/models/user.js
app/protected/template.hbs
app/reschedule/controller.js
app/reschedule/route.js
app/reschedule/template.hbs
app/router.js
app/styles/app.scss
tests/acceptance/reschedule-test.js
tests/integration/components/form-booking-filter/component-test.js
tests/unit/reschedule/controller-test.js
tests/unit/reschedule/route-test.js

This commit includes the possibility to reschedule a report of other users. The function is only available to staff users, which is a flag on the user model.
Furthermore the form filter was moved to its own component, which makes it more handy to use.

Feature to reschedule reports

---

.gitignore
README.md
app/analysis/controller.js
app/analysis/template.hbs
config/environment.js
ember-cli-build.js
package.json
tests/acceptance/analysis-test.js
yarn.lock

Give the possibility to configure the analysis export endpoints.
This PR is based on the #35 PR/Code, so please review #35 first.

Custom report export

---

app/analysis/controller.js

fix the case when no question mark in the base url is set

Download Link Join

---

app/me/route.js
app/me/template.hbs
app/models/absence-credit.js
app/models/absence-type.js
app/models/user-absence-type.js
app/models/user.js
app/styles/app.scss
app/utils/humanize-duration.js
mirage/config.js
mirage/factories/absence-credit.js
mirage/factories/absence-type.js
mirage/factories/user-absence-type.js
mirage/factories/user.js
mirage/models/absence-credit.js
mirage/models/user-absence-credit.js
mirage/models/user.js
mirage/scenarios/default.js
tests/unit/models/user-absence-type-test.js
tests/unit/utils/humanize-duration-test.js

* Show the absence types with credit, used and balance
* Show all credits on click
* Show used as duration for types with fill worktime

Display the absence credits correctly

---

app/mixins/report-filter-route.js
app/mixins/staff-route.js
app/protected/route.js
app/reschedule/route.js
mirage/factories/user.js
tests/acceptance/reschedule-test.js
tests/unit/mixins/staff-route-test.js

Fix reschedule access

---

app/mixins/report-filter-controller.js
app/mixins/report-filter-route.js
app/reschedule/controller.js
tests/acceptance/reschedule-test.js

This PR is almost the same as #54. I redid this because fixing the merge conflicts would've been more time expensive.

Reset filters when leaving the page

---

app/components/report-reschedule-row/template.hbs
app/components/report-row/component.js
app/components/report-row/template.hbs
app/components/tracking-bar/template.hbs
app/index/reports/template.hbs
app/styles/reports.scss
tests/acceptance/index-activities-test.js

* Added missing placeholder
* Don't allow editing of verified reports
* Focus comment field after selecting a task in timesheet

Minor UX fixes

---

app/analysis/template.hbs
app/components/task-selection/component.js
app/components/task-selection/template.hbs
app/components/user-selection/component.js
app/customer-suggestion/template.hbs
app/models/user.js
app/services/tracking.js
app/styles/app.scss

* Sort users
* Mark inactive users and archived customers / projects / tasks
* Show all filters on analysis page

Some cleanup and minor fixes

---

app/components/sy-durationpicker/component.js
app/components/sy-timepicker/component.js
app/components/task-selection/component.js
app/components/weekly-overview-day/styles.scss
app/index/attendances/controller.js
app/index/attendances/route.js
app/index/attendances/template.hbs
app/styles/app.scss
app/styles/attendances.scss
app/styles/ember-power-select-custom.scss
app/styles/reports.scss
app/validations/attendance.js
tests/integration/components/sy-timepicker/component-test.js

* Better timesheet / attendances styling for small devices
* Better validation for duration and timepicker
* Better highlighting of the selected day in the weekly overview

Some minor improvements

---

app/analysis/template.hbs
app/components/date-navigation/template.hbs
app/components/record-button/template.hbs
app/components/report-reschedule-row/template.hbs
app/components/report-row/component.js
app/components/report-row/template.hbs
app/components/sy-timepicker/component.js
app/components/sy-timepicker/template.hbs
app/components/tracking-bar/component.js
app/components/welcome-modal/template.hbs
app/index/activities/edit/controller.js
app/index/activities/edit/route.js
app/index/activities/edit/template.hbs
app/index/activities/template.hbs
app/index/attendances/template.hbs
app/index/reports/template.hbs
app/index/template.hbs
app/models/activity-block.js
app/reschedule/template.hbs
app/services/tracking.js
app/validations/activity-block.js
app/validators/moment.js
tests/acceptance/index-activities-edit-test.js
tests/acceptance/index-reports-test.js
tests/acceptance/index-test.js
tests/integration/components/report-reschedule-row/component-test.js
tests/integration/components/sy-durationpicker/component-test.js
tests/integration/components/sy-timepicker/component-test.js
tests/unit/validators/moment-test.js

* Add explicit types for all buttons
* Proper validations and changesets for activity blocks
* Some minor fixes for the time-/durationpicker

Fix activity editing and remove some unwanted sideeffects

---

.dockerignore
Dockerfile
contrib/nginx.conf

Build a docker container based on node that builds the final dist
and exposes it on port 80 using a basic nginx configuration.

Add docker build

---

app/users/edit/controller.js
app/users/edit/template.hbs
package.json

Use new API filter for the last valid timesheet worktime balance

---

app/components/balance-donut/styles.scss
app/components/worktime-balance-chart/component.js
app/index/controller.js
app/index/route.js
app/router.js
app/styles/app.scss
app/styles/users-navigation.scss
app/styles/users.scss
app/users/edit/index/controller.js
app/users/edit/index/route.js
app/users/edit/index/template.hbs
app/users/edit/template.hbs
mirage/config.js
tests/unit/users/edit/index/controller-test.js
tests/unit/users/edit/index/route-test.js

This is mostly HTML and CSS.. Not a lot of logic.

Add user profile general page

---

app/components/worktime-balance-chart/component.js
app/models/overtime-credit.js
app/router.js
app/styles/users.scss
app/transitions.js
app/users/edit/credits/controller.js
app/users/edit/credits/route.js
app/users/edit/credits/template.hbs
app/users/edit/template.hbs
package-lock.json
package.json
tests/acceptance/users-edit-credits-test.js
tests/acceptance/users-edit-test.js
tests/unit/users/edit/credits/controller-test.js
tests/unit/users/edit/credits/route-test.js

User profile credits tab

---

app/components/sy-sidenav/template.hbs
app/utils/format-duration.js

* Add missing sidenav item
* Fix format duration util

Minor fixes

---

app/users/edit/credits/absence-credits/edit/controller.js

Absence credit only no fill

---

app/users/edit/credits/index/controller.js
app/users/edit/credits/index/template.hbs

Always use a string for the year filter so comparisons whether an option is valid in the select box works

Year filter string

---

app/components/power-select/options/template.hbs
app/components/progress-tooltip/component.js
app/protected/template.hbs
app/styles/app.scss
package.json
yarn.lock

* Add `ember-concurrency` as dependency
* Style nav-wrapper instead of ember-view in the body so the tooltip which is has also the class ember-view does not get styled

Fix task selection box

---

app/users/edit/credits/absence-credits/edit/template.hbs
app/users/edit/credits/overtime-credits/edit/template.hbs

This way enter will save credit instead of canceling it.

Use native link for cancel button instead of button

---

.codecov.yml
README.md
yarn.lock

This is already assigned as a default in codecov.io itself.

Remove codecov.yml

---

app/abilities/report.js
app/analysis/controller.js
app/analysis/template.hbs
app/models/project.js
app/styles/analysis.scss
tests/acceptance/analysis-test.js
tests/unit/abilities/report-test.js
tests/unit/analysis/controller-test.js
yarn.lock

@sliverc Please check if the permission checking is done right (in `app/abilities/report.js`)

Make rows in analysis selectable

---

app/analysis/edit/controller.js
app/analysis/index/controller.js
app/components/filter-sidebar/template.hbs
app/statistics/controller.js
app/styles/filter-sidebar.scss
app/utils/query-params.js
tests/unit/utils/query-params-test.js

* Improve style and position of the filter toggle button
* Show the selected filters on said button
* Make filter sidebar scrollable
* Fix applied filter count on statistics page
* Always set editable filter to true on bulk edit
* Reset selected row on filter changes and reset

Fix various minor issues

---

app/analysis/edit/controller.js
app/analysis/edit/template.hbs
app/analysis/index/controller.js
app/components/task-selection/component.js
app/components/task-selection/template.hbs
app/validations/intersection.js
app/validators/intersection-task.js
tests/acceptance/analysis-test.js

* Validate bulk edit
* Reset task selection on bulk edit page too
* Don't reset selected rows on canceling bulk edit
* Always order by id too on analysis list

Fix various bugs

---

app/analysis/edit/controller.js
app/analysis/edit/template.hbs
app/components/changed-warning/component.js
app/components/changed-warning/template.hbs
app/components/task-selection/component.js
app/validations/intersection.js
app/validators/null-or-not-blank.js
tests/acceptance/analysis-edit-test.js
tests/integration/components/changed-warning/component-test.js
tests/unit/validators/null-or-not-blank-test.js

* Always show the not identical message
* Indicate changed values
* Validate comment

Fix states in bulk edit mask

---

app/analysis/edit/template.hbs

Fix typo in analysis/edit template

---

.gitignore
app/analysis/index/template.hbs
app/components/user-selection/component.js
app/statistics/template.hbs
app/users/index/template.hbs

Make the user-selection component generic, for query parameters.

Make user-selection generic

---

app/analysis/edit/controller.js
app/analysis/edit/template.hbs
app/analysis/index/template.hbs
tests/acceptance/analysis-edit-test.js
tests/acceptance/analysis-test.js

Instead of hiding the elements, they become disabled with a hover text.

Behaviour change for verify checkbox and edit all button 

---

app/components/tracking-bar/template.hbs

Make it read-only again while an activity is active.

Revert changes to tracking bar

---

app/analysis/edit/controller.js
app/analysis/index/controller.js
app/analysis/index/template.hbs
app/styles/analysis.scss
mirage/factories/project.js
mirage/factories/report.js
mirage/factories/task.js
tests/acceptance/analysis-edit-test.js

Also add highlighting of past edited reports.

Fix analysis, after update it doesnt set verifier

---

app/analysis/edit/controller.js
app/analysis/index/controller.js
tests/acceptance/analysis-edit-test.js
tests/acceptance/analysis-test.js

Change analysis edit to only make on get for all posts instead of patches for all
Fix analysis edit all to refresh store
Fix behavior of past selected to not accumulate

Improve analysis edit

---

app/analysis/edit/controller.js
app/analysis/index/controller.js
tests/acceptance/analysis-edit-test.js
tests/acceptance/analysis-test.js

Reverts adfinis-sygroup/timed-frontend#293

Revert "Improve analysis edit"

---

app/analysis/edit/controller.js
app/analysis/index/controller.js
tests/acceptance/analysis-edit-test.js
tests/acceptance/analysis-test.js

Reverts adfinis-sygroup/timed-frontend#294

Revert "Revert "Improve analysis edit""

---

app/analysis/edit/controller.js
app/analysis/index/controller.js
app/analysis/index/template.hbs
app/styles/analysis.scss
tests/acceptance/analysis-edit-test.js
tests/acceptance/analysis-test.js

Reverting this feature because there is a Problem with the pagination. It would need a different kind of Pagination to work.

Revert persistent scroll feature (#246, #281, #288, #295)

---

app/index/attendances/controller.js

Change variable in attendance controller, which was forgotten by #272.

Show correct attendance for selected day

---

app/application/authenticator.js

Rename data type for JWT login requests as needed by backend.
See: https://github.com/adfinis-sygroup/timed-backend/pull/502

chore(deps): adapt to backend jwt changes

---

app/application/authenticator.js

Depends on #367
Reverts #365
The change reverted here was incomplete and left me with a broken system.
I'll revisit the issue together with Stefan when he's back.

fix: token empty

---

app/analysis/edit/controller.js
app/analysis/index/controller.js
app/components/report-review-warning/component.js
app/components/report-review-warning/template.hbs
app/components/sy-topnav/component.js
app/components/sy-topnav/template.hbs
app/services/unverified-reports.js
tests/integration/components/report-review-warning/component-test.js
tests/unit/services/unverified-reports-test.js

The review warning is displayed to reviewers that haven't verified reports for last month or earlier yet.

feat(indicator): Show review warning for unverified reports

---

app/adapters/application.js
app/application/authenticator.js
app/services/ajax.js
mirage/config.js
tests/unit/services/ajax-test.js

Revisit of reverted PR https://github.com/adfinis-sygroup/timed-frontend/pull/365
* Update token handling to account for new tokens (access, refresh)
* Some minor refactoring

fix: adjust token handling

---

app/application/authenticator.js

For token refresh, get the refresh token from the session store.

fix(oidc): use refresh token from session store

---

app/analysis/index/controller.js
app/services/unverified-reports.js
mirage/config.js
tests/acceptance/analysis-edit-test.js

**Depends on** https://github.com/adfinis-sygroup/timed-backend/pull/527

fix(analysis): Adapt to JsonApiPageNumberPagination

---

app/projects/controller.js
tests/acceptance/project-test.js

A superuser should be able to edit tasks of all projects

fix(projects): Fetch all projects if superuser

---

app/projects/controller.js
app/projects/template.hbs
app/styles/projects.scss
tests/acceptance/project-test.js

There can be projects with the same name but under different
customers. Therefore the customers option is necessary.

fix(projects): Add customers option

---

app/projects/template.hbs

Add tag as required from the custom ember-power-select CSS

fix(projects): Quickfix design in dropdowns

---

package.json

Starting with `v0.13.1`, the first bugfix release in `v0.13` series.

chore(release): v0.13.1

---

app/services/unverified-reports.js

Change unverified reports query to use pagination to save resouces

fix(reports): change query to use pagination

---

app/application/authenticator.js

This will add a buffer which decreases the amount of time to wait
until the next refresh.

fix(session): Add buffer for token refresh

---

Dockerfile
config/environment.js
docker-entrypoint.sh

Quick fix for making sso config stuff injectable at runtime in a 12 factor(ish) fashion.

feat(oidc): runtime configurable oidc endpoint and client id

---

CODEOWNERS

Let's see how this works out. This here is more of an experiment than
a production setting. If it gains traction, we'll add it to more projects
in the future
See also adfinis-sygroup/timed-backend#634

feat: introduce code owners file

---

app/components/progress-tooltip/component.js
app/components/progress-tooltip/template.hbs
app/styles/progress-tooltip.scss

remove bottom progress bar in the progress tooltip

feat: add progress percentage for billable time

---

README.md
app/abilities/report.js
app/analysis/edit/controller.js
app/analysis/edit/template.hbs
app/analysis/index/controller.js
app/analysis/index/template.hbs
app/components/report-row/component.js
app/components/report-row/template.hbs
app/index/reports/controller.js
app/models/report-intersection.js
app/models/report.js
app/statistics/controller.js
app/statistics/template.hbs
tests/integration/components/report-row/component-test.js
tests/unit/abilities/report-test.js

Implements https://github.com/adfinis-sygroup/timed-backend/pull/670 in the frontend
Add billed filtering in analysis and statistics
Change editing permissions
Add billed to bulk edit

feat: add billed flag to report

---

CHANGELOG.md
package.json

Update missing Changelog while we're at it.

chore(release): v1.2.0

---

app/components/customer-visible-icon/component.js
app/components/customer-visible-icon/template.hbs
app/components/report-row/template.hbs
app/components/tracking-bar/template.hbs
app/index/activities/edit/template.hbs
app/index/activities/template.hbs
app/models/project.js
app/styles/app.scss
tests/integration/components/customer-visible-icon/component-test.js

add an icon to the comment field for customer visible projects

feat: visualise  customer visible projects

---

app/abilities/page.js
app/abilities/report.js
app/analysis/index/controller.js
app/models/customer-assignee.js
app/models/customer.js
app/models/project-assignee.js
app/models/project.js
app/models/task-assignee.js
app/models/task.js
app/projects/controller.js
mirage/config.js
mirage/factories/project-assignee.js
tests/acceptance/project-test.js
tests/unit/abilities/report-test.js

use assignees with reviewer role instead of project reviewers

feat: refactor reviewers

---

app/projects/controller.js
app/projects/template.hbs

Project and task should be reset when the customer changes. Task
should be reset when the project changes.

fix(projects): reset values when reapplying the filter

---

app/analysis/index/controller.js
app/analysis/index/template.hbs
tests/acceptance/analysis-test.js

**Performance fix:**
Until now, all assignees were fetched which resulted into significant
performance loss on the analysis page. With this, we fetch assignees
by the given tasks, projects or customers of the current page only.
**Feature**
Display reports only if filters are set

fix(analysis): various optimizations

---

app/analysis/edit/controller.js
app/analysis/edit/template.hbs
app/models/employment.js

An accountant is responsible for the billing of reports.
The feature "billing of reports" has already been implemented, but
we could not make use of it because of this missing role.

feat: introduce the missing accountant role

---

app/services/ajax.js

Until now, a blank screen was shown due to an unhandled exception.
This should redirect to login if the request to get the current user
returns a 401.

fix(auth): redirect to login on HTTP 401

---

app/index/controller.js
app/index/route.js
app/index/template.hbs
app/models/absence.js
app/users/edit/index/controller.js
app/users/edit/index/template.hbs
app/validations/absence.js
app/validations/multiple-absence.js
mirage/factories/absence.js

Timed-backend implemented following change: https://github.com/adfinis-sygroup/timed-backend/pull/861

fix(absence): rename type to absence_type

---

app/components/sy-checkmark/template.hbs
app/projects/controller.js
app/projects/route.js
app/projects/template.hbs
config/dependency-lint.js
package.json
pnpm-lock.yaml
tests/acceptance/project-test.js
tests/test-helper.js

*  e024bdc refactor(projects): octanify ~~controller~~ everything
---
> 21th PR of [this series](https://github.com/adfinis/timed-frontend/pulls/710) #710.
> **Only merge when #749 is merged and this PR got rebased!**

refactor(projects): octanify controller

---

app/adapters/application.js
app/components/sy-topnav/template.hbs
app/protected/controller.js
app/protected/template.hbs

* redirect to `login` on `401` responses
* call correct action on `logout` click

fix(auth): improve invalid session handling

---

README.md
docker-compose.yml

The image will be built via workflow and pushed to ghcr in the future. Made it more visible with the status badge.

docs(readme): give a hint to ghcr container image

---

app/analysis/edit/template.hbs
app/analysis/index/controller.js
app/analysis/index/template.hbs
app/components/report-review-warning/component.js
app/components/report-review-warning/template.hbs
app/components/user-selection/component.js
app/models/report-intersection.js
app/models/report.js
app/services/rejected-reports.js
app/services/tracking.js
app/styles/analysis.scss
app/styles/app.scss
tests/unit/services/rejected-reports-test.js

closes #730 
**This branch is based on #770 and should be rebased before merging.**

feat: reject report

---

app/components/optimized-power-select/component.js
app/components/optimized-power-select/template.hbs
app/components/task-selection/component.js
tests/helpers/tracking-mock.js
tests/integration/components/task-selection/component-test.js
tests/integration/components/tracking-bar/component-test.js

* enter + tab key navigation pattern got re-enabled
* #802

fix: customer select

---

app/services/rejected-reports.js

fix(reject-report): show all rejected reports

---

app/adapters/application.js
app/analysis/index/controller.js
app/services/fetch.js
tests/helpers/session-mock.js
tests/unit/services/fetch-test.js

* delete `handleResponse` override in application adapter
* refactor auth headers in `fetch` service

fix: delete unneeded oidc adapter overrides and simplify other auth procedures

---

app/analysis/index/controller.js

fix(analysis): re-enable downloading exports

---

app/components/record-button/template.hbs
app/styles/components/record-button.scss
tests/acceptance/index-test.js

Fixes #820 
Includes:
* record button proportions on various screen sizes
* tidy up class definitions
* center play icon on record button via small transformation

fix(record-button): layout on different view port sizes

---

.github/workflows/release-npm.yml
package.json
pnpm-lock.yaml

Repair the existing `semantic-release` setup by reinstalling the packages and updating the workflow.

ci(semantic-release): repair workflow setup

---

app/index/route.js

fix(reports): include user to resolve name of verifier

---

app/index/activities/edit/template.hbs

fix(activity-edit-form): update task selection on model change

---

app/analysis/edit/controller.js
app/analysis/edit/route.js
app/analysis/edit/template.hbs

fix: bulk report form reset

---

app/projects/template.hbs
app/styles/projects.scss

feature: the archived project will have gray background color instead of blue color

feat: gray background color for the archived projects

---

package.json
pnpm-lock.yaml

https://github.com/adfinis/ember-simple-auth-oidc/releases

chore: upgrade ember-simple-auth-oidc

---

app/components/date-buttons/template.hbs
app/components/filter-sidebar/label/template.hbs
app/components/tracking-bar/template.hbs
app/components/weekly-overview/template.hbs

this PR have include the fix of some warnings in ember templates

Fix hbs warning

---

app/components/report-row/component.js
app/index/route.js

fix: report verifier is not defined

---

package.json
pnpm-lock.yaml

chore(deps): upgrade ember-simple-auth-oidc to v5.0.3

---

app/index/route.js

fix: attendances added wrong day after page refresh

---

app/analysis/edit/controller.js
app/analysis/edit/template.hbs
tests/acceptance/analysis-test.js

Fixes #889 
Reverts some of https://github.com/adfinis/timed-frontend/commit/fe2d199fad2c95e0faf382087869a67daca14793

fix(analysis): enlarge accountants bulk editing capabilities

---

app/index/attendances/template.hbs

fix(attendance-slider): update validation status before saving

---

app/services/tracking.js

fix: fetching the correct project tasks

---

app/components/customer-visible-icon/template.hbs

fix(customer-visible-icon): splatter attributes

---

app/models/absence-balance.js
app/models/absence-credit.js
app/models/absence-type.js
app/models/absence.js
app/models/attendance.js
app/models/billing-type.js
app/models/cost-center.js
app/models/customer-assignee.js
app/models/customer.js
app/models/employment.js
app/models/location.js
app/models/month-statistic.js
app/models/project-assignee.js
app/models/public-holiday.js
app/models/report-intersection.js
app/models/task-assignee.js
app/models/user-statistic.js
app/models/user.js
app/models/worktime-balance.js
app/models/year-statistic.js

use native JS classes in timed models

Native js classes in ember models

---

app/abilities/report.js
tests/unit/abilities/report-test.js

fix: verified reports shold not be editable

---

pnpm-lock.yaml

Ideally all devs update their `pnpm` version `v8`.

chore(pnpm): update lockfile to version 6 (comes with pnpm v8)

---

app/users/edit/credits/absence-credits/edit/controller.js
app/users/edit/credits/index/controller.js
app/users/edit/credits/overtime-credits/edit/controller.js

I've messed up the latest release (pnpm version conflict) and needed some changes to commit to trigger a release (with the corrected pnpm version which was only a `chore` commit)... 
So I went with fixing some linting errors.

fix: simply to trigger a release

---

app/analysis/edit/controller.js
app/analysis/edit/route.js
app/analysis/index/controller.js
app/analysis/index/route.js
app/analysis/index/template.hbs
app/statistics/controller.js
app/statistics/route.js
app/statistics/template.hbs
app/utils/query-params.js
app/utils/serialize-moment.js
package.json
pnpm-lock.yaml
tests/acceptance/analysis-edit-test.js
tests/acceptance/analysis-test.js
tests/acceptance/auth-test.js
tests/unit/utils/query-params-test.js

chore: remove ember parachute

---

app/components/sy-durationpicker-day/template.hbs

fix(sy-duration-picker-day): respect disabled flag

---

app/analysis/index/controller.js
app/analysis/index/route.js
app/analysis/index/template.hbs
app/components/report-review-warning/template.hbs
app/controllers/qpcontroller.js
app/statistics/controller.js
app/statistics/template.hbs

fix: analysis route query parameter updates reload data

---

app/components/attendance-slider/component.js

fix: `htmlSafe` function import path

---

app/components/report-row/template.hbs
app/components/tracking-bar/template.hbs
app/index/activities/edit/template.hbs

feat: enforce spelling check for comment field

---

app/analysis/index/template.hbs
app/components/task-selection/component.js

fix(TaskSelection): reset component filter when updating the page controller properties
