adfinis/timed-frontend

app/components/sy-timepicker/component.js, app/components/sy-timepicker/template.hbs, app/index/activities/edit/template.hbs, app/index/activities/route.js, app/index/activities/template.hbs, app/models/activity-block.js, app/models/activity.js, app/serializers/activity.js, mirage/factories/activity-block.js, mirage/factories/activity.js, tests/acceptance/index-activities-test.js
* User gets a warning when trying to generate a timesheet with an activity which overlaps the day
* Overlapping activities and blocks are highlighted
* Help texts for the user
* Field `start-datetime` was renamed in the backend to `date` for better understanding
=> Overlaping activities

app/components/sy-modal/overlay/component.js, app/components/sy-modal/template.hbs, app/index/controller.js, app/index/route.js, tests/acceptance/index-test.js, tests/integration/components/sy-modal/overlay/component-test.js
* Rollback the modal data after closing it
* Set the center of the calendar to the selected date
* Preselect the selected date in the new absence calendar
=> Minor absence modal fixes

app/index/activities/route.js, app/models/activity.js, app/services/tracking.js
Before this fix, the date on an activity was set while creating it. This resulted in unsaved activities which had a date of a past day so after saving it, it had a way too long duration.
=> Set the date of an activity before starting it the first time

app/components/sy-sidenav/template.hbs
We don't need to show everyone the users list, since those who can actually see users there can access them over the responsibility tab in their profile.
=> Only show users list to superuser

app/components/date-buttons/styles.scss, app/components/date-buttons/template.hbs
The last date button was previously being pushed underneath the others.
=> Fix style for date buttons

app/index/reports/controller.js, testem.js
Reports that are not new should preserve their sorting order instead of
resorting. This should prevent a newly created report from being moved
to the top in Chrome.
Also, use Chrome instead of Chromium to run tests in CI.
=> Fix different behavior between Chrome and Firefox

app/analysis/index/template.hbs, app/components/date-buttons/component.js, app/statistics/template.hbs, tests/integration/components/date-buttons/component-test.js
This will allow to filter reports by last week, last month and last
year in Analysis and Statistics.
=> Add additional filter options for reports

app/index/controller.js
This fixes the 'jumping' activity sum in the tab badge.
The problem was that there was a timer (1s) to compute the duration of the currently active activity. I changed this to recompute the duration before it is used to calculate the total sum.
Plus, some refactoring of abbreviated variable names.
=> fix(activities): correct activity sum computation

tests/integration/components/progress-tooltip/component-test.js
Changed the label also in the tests. Change in the component was done with https://github.com/adfinis-sygroup/timed-frontend/pull/395
=> fix: budget instead of estimate in progress tooltip

app/components/progress-tooltip/template.hbs, tests/integration/components/progress-tooltip/component-test.js
"Budget" seems more appropriate than "Estimate" and was also specified in the feature request for the progress tooltip
=> fix: budget label instead of estimate in progress tooltip

app/services/tracking.js
Since it's the same request on each report, it needs to be fetched
only once. This will highly optimize the performance and UX.
=> fix(tracking): Fetch most frequent tasks only once

app/styles/ember-power-select-custom.scss
The syntax with multiple arguments for :not() is not well supported
yet
=> fix(reports): Apply pseudo-class correctly

yarn.lock
It's not described in their changelog but bumping the version will fix the issue where an empty scrollbar is displayed at the bottom after visiting a page that uses this addon.
Tested locally on `/analysis` and `/projects`
=> chore(deps): Update ember-scrollable

package.json
This should fix the dependents on [the dependant overview](https://github.com/adfinis-sygroup/timed-frontend/network/dependents) from dependabot.
Given that there is a `timed` package on npm that does some timing stuff we should mark ours private.
This was introduced years ago in #98 with 7c5ba7163f4d250721391b905e8ecffcf2bfea04.
=> fix: mark package private so it won't get used as dependent

CODEOWNERS
I think it's more reasonable to leave notifications up to personal configuration. A large part of the frontend team is not working actively on this project, and the code ownership generates unnecessary notifications.
=> chore: drop CODEOWNERS file

package.json, yarn.lock
`ember-cli-uglify-es` is outdated which results into failing
production builds.
=> chore(deps): use ember-cli-uglify instead of ember-cli-uglify-es

app/components/page-permission/component.js, app/components/page-permission/template.hbs
This is needed otherwise it breaks the view on analysis and
statistics.
=> fix(view): make page-permission a tagless component

app/analysis/index/controller.js
The inclusion of the models is important to avoid each task,
project or customer being fetched individually, which would have a
really bad impact on the performance as well.
fixes #586
=> fix(analysis): include relevant models for assignees

package.json, yarn.lock
This dependency is not necessary and making trouble in production
builds.
=> chore(deps): remove ember-cli-uglify

app/analysis/index/controller.js
This fixes the ugly performance issue on the analysis page where loading of an **empty** list was unbelievably slow..
=> fix(analysis): only fetch assignees if there are IDs given

app/abilities/report.js, tests/acceptance/analysis-test.js
This fixes the issue where the reports had to be verified AND billed in order to
make them non-editable. The reports should not be editable once
they are verified OR billed.
=> fix(analysis): do not allow to edit reports once they are verified

app/analysis/edit/template.hbs, app/components/report-row/template.hbs, app/components/tracking-bar/styles.scss, app/index/activities/edit/template.hbs, app/index/activities/template.hbs, app/styles/app.scss
added customer-visible-icon to analysis-edit
preview of the change:
- analysis-edit report
- activities index/edit
- tracking-bar, timesheet index
=> fix(styling): fix overlapping eye-icon in comment field

app/no-access/route.js, app/no-access/template.hbs, app/protected/route.js, app/router.js, tests/unit/no-access/route-test.js
Only users with an internal or external employment are allowed to
access timed. Users such as customers will be forwarded to the new
`no-access` page, where a message will be displayed that they do
not have the permission to access Timed.
=> feat: create view for users with no permission

app/analysis/edit/controller.js, app/analysis/edit/template.hbs, app/analysis/index/controller.js, app/analysis/index/template.hbs, app/models/report-intersection.js, app/models/user.js, mirage/factories/user.js, tests/acceptance/analysis-test.js, tests/unit/abilities/report-test.js
This will allow accountants to bill reports on analysis-edit. All
form elements except the `billed` checkbox will be disabled
if at least 1 report has been selected that was not created by the
accountant.
=> feat(analysis): accountants may bill reports

.husky/commit-msg, .husky/pre-commit, package.json, yarn.lock
- setup two husky jobs (lint-staged and commitlint)
The contents of this PR start at 42deec6413aa9982597fb19cb299b509ed245183
Commits before belong to #713
---
> 4th PR of [this series](#710).
> **Only merge when #713 is merged and this PR got rebased!**
---
=> ci: re-setup pre-commit linting

app/components/report-row/template.hbs, app/components/sy-durationpicker-day/template.hbs, app/components/sy-durationpicker/template.hbs, app/index/activities/template.hbs, app/index/controller.js, app/index/route.js, app/protected/route.js, mirage/factories/activity.js, tests/acceptance/index-activities-test.js, tests/integration/components/sy-durationpicker/component-test.js
* a19d9fe test(activities): skip test for until further investigation
* c519555 fix(sy-durationpicker): re-add name attribute
* 16461ab test(activity): fix active trait
* 1b93ee1 fix(modal-footer): add missing data-test attribute
* 7f52475 fix(report-row): assign passed attributes to row
* 6d62c65 test(activities): lax current url check
* a888a95 fix(activities): small improvements
With a19d9fe I want to invite you, dear reviewer, to investigate with me, why this test is failing with the wrong `report-row-id`. I could not figure out and therefore skipped the test.
---
> 18th PR of [this series](https://github.com/adfinis/timed-frontend/pulls/710) #710.
> **Only merge when #743 is merged and this PR got rebased!**
=> fix: mainly fix broken tests

Dockerfile
Correct me if I'm wrong, but `yarn` shouldn't be used as we switched to `pnpm`.
Not sure if I'm instaling it correctly though.
There's also an option to [fetch](https://pnpm.io/cli/fetch) packages to boost build time. Is this something we could use?
=> chore: use pnpm in Dockerfile

.github/workflows/test.yml
* add no-frozen-lockfile parameter to install step
* deletes workflow runs on ember-octane branch
* re-enables codecov reporting
=> ci: adapt test workflow to pnpm setup

.github/workflows/release.yml, .github/workflows/test.yml, package.json
* Updates all actions to their latest version. This way we get `node 16` by default, still allowing for specific overrides.
* Further it improves the ci workflow by cleaning the `test` script defined in the `package.json`.
* Update and re-enable codecov action. This way future PRs have to at least improve the coverage and we are back in the coverage game. This leads to **failing CI tests for this PR!!** Please ignore the codecov jobs in this PR. The coverage compares with the last available upload which dates back to this commit d45179d.
* The formerly introduced change to the workflow triggers (`$default-branch` in #762 ) got reverted, since this variable is only available in workflow templates.
=> ci: upgrade workflow actions to use node 16 by default

app/styles/filter-sidebar.scss
When using filters the screen isn't greyed out, leading to not being able to click anywhere on the screen to hide the filter menu.
Raise z-index when overlay is visible.
=> fix(filter-sidebar): raise z-index for overlay when visible

app/components/sy-durationpicker/component.js
As this component extends the `sy-timepicker` component, we have to override the `value` getter, which would otherwise initiate a `moment` object instead of a `moment.duration` for the duration picker, which leads to wild behavior of the component.
=> fix(sy-durationpicker): create duration if none is passed

app/analysis/edit/controller.js, app/analysis/index/controller.js, app/protected/route.js, app/services/fetch.js, tests/acceptance/analysis-edit-test.js, tests/acceptance/analysis-test.js
Sorting the analysis table via clicking on the `Date` header does not trigger the ordering change.
Do not serialize the `ordering` QP to `null`, if it's equal to the default value (`-date,id`)
When entering `/analysis` the default query parameter for `ordering` should be `-date` which results in a serialized `-date,id` QP. As long as the QP is equal to it's default value, it should not occur in the URL. So far so good. 
But somehow, the QP will be present in the URL event though it's equal to the default value in the acceptance tests for `Acceptance | analysis edit: can edit`. :( 
Ergo we have to adapt the test-assertion or tune the QP more. What do you think @velrest ?
=> fix(analysis): table sorting according to ordering qp

app/analysis/index/controller.js, app/analysis/index/template.hbs
Fixes #727 
* makes `totalTime` and `totalItems` a tracked property, otherwise updates of the template were unpredictable
* uses the correct `reports` reference in the template
=> fix(analysis): show number of displayed reports

.github/workflows/release-image.yml, .github/workflows/release-npm.yml
Push the image automatically to ghcr.io [similar to the backend](https://github.com/adfinis/timed-backend/commit/0c3fa09322908f20a63db2561dd665036b5bea0f)
=> chore(ci): publish container image to ghcr.io

.github/dependabot.yml, .github/workflows/release-image.yml
* update github action, which upgrades internally to node ~~12~~ 16
* remove dependabot config since [we are using renovate now](https://github.com/adfinis/timed-frontend/pull/779)
=> ci: update github actions

app/components/statistic-list/bar/template.hbs, app/components/statistic-list/template.hbs, app/models/task-statistic.js
**Follow up after #721**
The bar chart would show the goal and remaining effort even if it's not defined/enabled on the task/project, like shown in the screenshot. This behavior is not intended and the red dotted "goal line" should not be visible if no estimed time is given.
=> fix(statistic-list-bar): improve bar graph representation

.github/workflows/test.yml
Branches opened by renovate need to run through the test workflows before automerge can proceed.
This [configuration is endorsed by renovate](https://docs.renovatebot.com/key-concepts/automerge/#branch-vs-pr-automerging).
=> chore(test-workflow): add renovate branches

app/statistics/controller.js, tests/acceptance/statistics-test.js
The customer-statistics request is quite demanding to for the backend. Especially on our test instance with only one pod this leads to very long waiting times or crashes of the backend. That's why we want to make the `fromDate` query param required for the customer statistics view.
=> fix(customer-statistics): require fromDate param

app/analysis/index/template.hbs, app/components/filter-sidebar/group/styles.scss
And increase max-height since we added the rejected filter and the last filter was not visible anymore.
=> fix(filter-sidebar): reorder available filter

app/index/reports/controller.js
This prevents *already verified* reports from being *temporarily* (namely until the next hard refresh) to be transferred, although they can not get transferred when verified.
Includes a verbose warning message for the user. => UX :one: :up: 
Fixes #807
=> fix(reports): check if reports got verified before transfer

app/components/progress-tooltip/component.js, app/services/metadata-fetcher.js
The tooltip information was stale when task related remaining effort got updated after initial loading of the task/report page. 
I preferred to expand the `metadata-fetcher-service` for fetching fresh information on the project/task status instead of adding another request for updating the model in store. The meta-data request has to be made anyways and updating the model in question would only double up the request count. *Feedback welcome!*
=> fix(remaining-effort): extract fresh info for tooltip

app/components/report-review-warning/template.hbs, app/services/rejected-reports.js, app/styles/app.scss, config/icons.js
The frontend should warn the user who created the wrong report about the rejection. Not the reviewer.
Further this fixes the icon used for the warning.
=> fix(reject-report): display rejected reports to responsible

app/projects/template.hbs, app/styles/projects.scss
We still need the `billingType` valdations for patches on the `projects` endpoint. To show the users they can't update the project (toggle remaining effort tracking checkbox), we show a warning icon with the error as hover description. See attached screenshot for final UI.
*warning icon on projects page*
*warning icon hovered*
=> fix(remaining-effort): display validation errors in project view

app/components/statistic-list/bar/template.hbs, app/components/statistic-list/component.js, app/components/statistic-list/template.hbs, tests/acceptance/statistics-test.js
Adds the remaining-effort feature to the *by project* tab of the statistics page. Lately we added it only to *by task* tab.
=> feat(remaining-effort): add re feature to project statistics

app/components/report-row/component.js, app/services/tracking.js
The `dropTask` modifier prevented multiple instances of the `TaskSelect` component in the timesheet overview from fetching their data for the dropdown. With the renewed logic, it will prevent fetching the same query multiple times.
=> fix(tracking-service): replace drop task modifier

app/components/sy-topnav/template.hbs, package.json
Fixes #825 
`pre-releases` do not trigger semantic-release normally, so we have to bump it manually for now.
We'll investigate if we could leverage the `semantic-release` package also for the `pre-release` trigger.
See the [ember-cli-app-version docu](https://github.com/ember-cli/ember-cli-app-version#app-version-helper) for convenience.
=> chore: bump displayed version to 3.0.0-rc

app/components/task-selection/component.js, app/components/task-selection/template.hbs, tests/integration/components/task-selection/component-test.js
Fixes #838 and #839 
The previously refactored task-selection component, did not filter the respective projects and tasks for their current `archived` status. This yielded way more results in the dropdown as expect. Further those results where not ordered and that's why it seemed like it shows some *recent projects / tasks* which in reality, where just the first entries which got previously fetched to the store by other components of the app (e.g. timesheet).
=> fix(task-selection): respect archived filter

app/projects/controller.js, app/projects/template.hbs
Further fix a bug where one could not reset the customer select.
This fixes a bug report from @anehx who was missing the search functionality on the project page' selects.
=> fix(projects): enable search in customer and project selects

app/components/task-selection/component.js, config/icons.js, tests/integration/components/tracking-bar/component-test.js
Fixes #852 
When selecting a *recent task* (history) then we still need to load all available projects for the indirect selected customer. Otherwise the list of projects will be incomplete.
=> fix(task-selection): fill selects with available entries

app/components/progress-tooltip/component.js, app/components/sy-durationpicker/component.js, app/projects/controller.js, app/projects/template.hbs, app/styles/projects.scss, tests/integration/components/progress-tooltip/component-test.js
Adding or editing tasks on projects page will no longer yield side effects, namely changing the `remaining-effort` of the task even if it was not enabled on the project.
Further fixes: 
* won't show remaining effort in progress tooltips
* repairs the table layout for the tasks of the project
* changes behavior of the `sy-durationpicker` component to allow values equal to `max` or `min`. That allows to `00:00` fields like the remaining effort input.
Fixes #851
=> fix: adding or editing tasks on projects page

app/components/weekly-overview/template.hbs, app/index/controller.js, app/index/template.hbs
The formerly implemented tracked task did not properly refresh on store updates, so we switched to a tracked function.
Fixes #855
=> fix(weekly-overview): refresh weekly overview graph

.husky/commit-msg
It blocks releases since the body line is certainly longer than 100 characters.
=> ci: disable commitlint in ci

app/analysis/index/controller.js
We can utilize the ember concurrency animationFrame method instead of writing our own request-animation-frame util.
https://ember-concurrency.com/api/global.html#animationFrame
=> refactor(analysis): use ec animationframe util

app/index/attendances/controller.js, app/index/attendances/template.hbs, app/validations/attendance.js, app/validators/moment.js, tests/unit/validators/moment-test.js
fix of #885 
the validation was checking the value in the changes, which was an empty object,
since an empty object was a valid value, (`undefined` and `null` are not acceptable), that's why the comparative was between moment instance and an empty object
=> fix: negative activities possible

app/components/task-selection/component.js, app/index/activities/edit/controller.js, app/index/activities/edit/template.hbs
Fixes #891 
* multiple selection of a recent task won't reset project & task
* initial selection will now resolve proxies to determine state (this decides whether to fetch all customers initially or not)
=> fix(task-selection): make selection more robust

app/index/activities/edit/controller.js
Fixes #892 
[Hint to the disabled eslint rule](https://eslint.org/docs/latest/rules/no-await-in-loop#when-not-to-use-it)
=> fix(activities): dont delete records while in flight

Dockerfile
As long as we depend on `danlynn/ember-cli:3.28.5` we are bound to `node v16.13.1`. But since v8 `pnpm` requires at least `node v16.14`. As temporary resolution we have to pin `pnpm` to v7.
This is [blocking the ghcr image job](https://github.com/adfinis/timed-frontend/actions/runs/4617203705/jobs/8163238354).
=> chore(dockerfile): pin pnpm to v7

app/controllers/qpcontroller.js, app/users/index/controller.js, app/users/index/route.js, tests/unit/controllers/qpcontroller/controller-test.js
As we want to move away from `ember-parachute` #723 , we have to handle query params by our own. Extracting those util methods to a generic controller is the first step to refactor all the other controllers currently depending on `ember-parachute` mixins.
Further this PR reverts a accidental change, where the QPs of the `users/index` controller where listed in the route query params hash separately.
=> refactor(users): extract query param utils to generic controller

app/protected/route.js
We should await the `auth` response, before proceeding with further requests in the protected route. Otherwise it is more prune for race-conditions in the auth flow. Full description see: https://github.com/adfinis/ember-simple-auth-oidc/pull/761
=> fix(protected): await before model hook auth request

app/analysis/index/template.hbs, app/components/sy-checkmark/template.hbs, app/index/activities/template.hbs, app/styles/analysis.scss, app/styles/components/sy-toggle.scss, tests/integration/components/sy-checkmark/component-test.js
=> fix: add glimming to the checked boxes in analysis & timesheet

.npmrc, pnpm-lock.yaml
This helps keeping the settings for pnpm v7 and lockfile version v6 in line while also using dependabot for updates. Otherwise it would overwrite the 'autoInstallPeers' setting, as dependabot may use a different pnpm version. This specific setting is obsolete as soon as we update to pnpm v8.
See https://github.com/pnpm/pnpm/issues/6649 for more info.
=> chore(pnpm): add npmrc config file

app/components/report-row/component.js, app/components/report-row/template.hbs
=> fix(report-row): components from duplication when clicking submit

app/validators/intersection-task.js
=> fix: updating the customer, project, task in analysis edit report page

app/analysis/edit/controller.js, app/models/report-intersection.js
=> fix: verify rejected reports

app/index/reports/route.js
Magic links now respect remaing effort estimates.
Resolves #1182
=> fix: respect last value for remaining efforts for magic links

app/analysis/index/route.js, app/components/task-selection/component.js, tests/acceptance/analysis-test.js
Restore the selection feature which was lost while refactoring.
https://github.com/adfinis/timed-frontend/blob/d0cb64e0b9f8bd37d5b92144127dc5b1b5dbac80/app/analysis/index/controller.js#L204C9-L204C38
=> fix(analysis): skip reset if edit is cancled

app/analysis/edit/route.js
=> fix: resetting `analysis.edit` query params
